version: "3.7"
services:
  next:
    build:
      args:
        - NODE_VER=22.12.0
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/my-app/node_modules
volumes:
  node_modules:
